openapi: 3.0.0
info:
  title: M3_ContentHostingProvisioning
  version: 3.0.0
  description: |
    5GMS AS M3 Content Hosting Provisioning API
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
tags:
  - name: M3_ContentHostingProvisioning
    description: '5G Media Streaming: Application Server Configuration (M3) APIs: Content Hosting Provisioning'
externalDocs:
  description: 'TS 26.512 V18.y.z; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'
servers:
  - url: '{apiRoot}/3gpp-m3/v3'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 29.512 clause 6.1.
paths:
  /content-hosting-configurations:
    summary: "Content Hosting Configuration collection"
    get:
      operationId: retrieveContentHostingConfigurations
      summary: "Retrieve a list of Content Hosting Configuration resource identifiers currently registered with the 5GMS AS"
      responses:
        '200':
          # OK
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        '400':
          # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /content-hosting-configurations/{provisioningSessionId}:
    summary: "Operations to manipulate a single Content Hosting Configuration resource"
    description: "Individual Content Hosting Configuration resources in the collection are addressed by the provisioningSessionId of their parent Provisioning Session."
    parameters:
      - name: provisioningSessionId
        in: path
        required: true
        schema:
          $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of an existing Provisioning Session.'
    post:
      operationId: createContentHostingConfiguration
      summary: 'Create and upload the Content Hosting Configuration for the specified Provisioning Session'
      requestBody:
        description: 'A JSON representation of a Content Hosting Configuration'
        required: true
        content:
          application/json:
            schema:
              $ref: 'TS26512_M1_ContentHostingProvisioning.yaml#/components/schemas/ContentHostingConfiguration'
      responses:
        '201':
          # Created
          description: 'Content Hosting Configuration Created'
          headers:
            Location:
              description: 'URL of the newly created Content Hosting Configuration (which may be redirected from the request URL).'
              required: true
              schema:
                $ref: 'TS26512_CommonData.yaml#/components/schemas/AbsoluteUrl'
        '400':
          # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '409':
          # Conflict: Content Hosting Configuration resource already exists at the specified path
          $ref: 'TS29571_CommonData.yaml#/components/responses/409'
        '411':
          # Length Required
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          # Payload Too Large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'   
    # get (Retrieval of individual Content Hosting Configuration resources is not permitted at reference point M3.)
    put:
      operationId: updateContentHostingConfiguration
      summary: 'Update (by replacement) an existing Content Hosting Configuration for the specified Provisioning Session'
      requestBody:
        description: 'A JSON representation of a Content Hosting Configuration'
        required: true
        content:
          application/json:
            schema:
              $ref: 'TS26512_M1_ContentHostingProvisioning.yaml#/components/schemas/ContentHostingConfiguration'
      responses:
        '200':
          # OK
          description: 'Content Hosting Configuration Updated'
        '204':
          # No Content
          description: 'Content Hosting Configuration Unchanged'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Hosting Configuration resource has been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '411':
          # Length Required
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          # Payload Too Large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default' 
    delete:
      operationId: destroyContentHostingConfiguration
      summary: 'Destroy the specified Content Hosting Configuration'
      responses:
        '204':
          # No Content
          description: 'Content Hosting Configuration Destroyed'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Hosting Configuration resource has already been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /content-hosting-configurations/{provisioningSessionId}/purge:
    parameters:
        - name: provisioningSessionId
          in: path
          required: true
          schema:
            $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
          description: "The Provisioning Session identifier of an existing Content Hosting Configuration."
    post:
      operationId: purgeContentHostingCache
      summary: 'Purge the content of the cache for the specified Content Hosting Configuration'
      requestBody:
        description: "The regular expression pattern for resources to purge from the cache."
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                pattern: 
                  description: 'Regular expression to match URL in cache entry'
                  type: string
      responses:
        '200':
          # OK
          description: 'Content Purged'
          content:
            application/json:
              schema:
                type: integer
                description: 'Number of cache entries purged'
                minimum: 1
        '204':
          # No Content
          description: 'No Content Purged'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Hosting Configuration resource has been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '413':
          # Payload Too Large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '422':
          # Unprocessable Content: Regular expression in request body could not be processed by the 5GMS AS
          description: 'Unprocessable Content'
          content:
            application/problem+json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/ProblemDetails'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
