openapi: 3.0.0
info:
  title: M3_ContentPreparationTemplatesProvisioning
  version: 3.0.0
  description: |
    5GMS AS M3 Content Preparation Templates Configuration API
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
tags:
  - name: M3_ContentPreparationTemplatesProvisioning
    description: '5G Media Streaming: Application Server Configuration (M3) APIs: Content Preparation Templates Provisioning'
externalDocs:
  description: 'TS 26.512 V18.y.z; 5G Media Streaming (5GMS); Protocols'
  url: 'https://www.3gpp.org/ftp/Specs/archive/26_series/26.512/'
servers:
  - url: '{apiRoot}/3gpp-m3/v3'
    variables:
      apiRoot:
        default: https://example.com
        description: See 3GPP TS 29.512 clause 6.1.
paths:
  /content-preparation-templates:
    summary: "Content Preparation Templates collection"
    get:
      operationId: retrieveContentPreparationTemplates
      summary: "Retrieve a list of Content Preparation Template resource identifiers currently registered with the 5GMS AS"
      responses:
        '200':
          # OK
          description: "Success"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        '400':
          # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /content-preparation-templates/{afContentPreparationTemplateId}:
    summary: "Operations to manipulate a single Content Preparation Template resource"
    description: "Individual Content Preparation Template resources in the collection are addressed using an afContentPreparationTemplateId generated by the 5GMS AF which is guaranteed to be unique across all provisioning sessions."
    parameters:
     - name: afContentPreparationTemplateId
       in: path
       required: true
       schema:
         $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
       description: "The resource identifier, assigned by the 5GMS AF, of the target Content Preparation Template. Unique for all content preparation templates in the 5GMS System."
    post:
      operationId: createContentPreparationTemplate
      summary: "Create a new Content Preparation Template resource and populate it with the representation provided in the request body"
      requestBody:
        description: "A Content Preparation Template of any content type supported by the 5GMS AS."
        required: true
        content:
          '*/*':
            schema:
              type: string
      responses:
        '201':
          # Created
          description: "Content Preparation Template Created"
          headers:
            Location:
              description: "URL of the newly created Content Preparation Template resource (which may be redirected from the request URL."
              required: true
              schema:
                $ref: 'TS26512_CommonData.yaml#/components/schemas/AbsoluteUrl'
        '400':
          # Bad Request: The syntax of the HTTP request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '409':
          # Conflict: Content Preparation Template resource already exists at the specified path
          $ref: 'TS29571_CommonData.yaml#/components/responses/409'
        '411':
          # Length Required
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          # Payload Too Large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'   
     # get (Retrieval of individual Content Preparation Template resources is not permitted at reference point M3.)
    put:
      operationId: updateContentPreparationTemplate
      summary: "Update (by replacement) an existing Content Preparation Template resource with a new representation"
      requestBody:
        description: "A Content Preparation Template of any content type supported by the 5GMS AS."
        required: true
        content:
          application/x-pem-file:
            schema:
              type: string
      responses:
        '200':
          # OK
          description: "Content Preparation Template Updated"
        '204':
          # No Content
          description: 'Content Preparation Template Unchanged'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Preparation Template resource has been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '411':
          # Length Required
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          # Payload Too Large
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default' 
    delete:
      operationId: destroyContentPreparationTemplate
      summary: 'Destroy an existing Server Certificate resource'
      responses:
        '204':
          # No Content
          description: 'Content Preparation Template Destroyed'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Preparation Template resource has already been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /content-preparation-templates/{afContentPreparationTemplateId}/activate:
    parameters:
      - name: afContentPreparationTemplateId
        in: path
        required: true
        schema:
          $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of the Content Preparation Template to be activated.'
    post:
      operationId: activateContentPreparationTemplate
      summary: 'Activate a Content Preparation Template'
      responses:
        '202':
          # Accepted
          description: 'Activation of Content Preparation Template in progress'
        '204':
          # No Content
          description: 'Content Preparation Template activated and ready for use'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Preparation Template resource has been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /content-preparation-templates/{afContentPreparationTemplateId}/deactivate:
    parameters:
      - name: afContentPreparationTemplateId
        in: path
        required: true
        schema:
          $ref: 'TS26512_CommonData.yaml#/components/schemas/ResourceId'
        description: 'The resource identifier of the Content Preparation Template to be deactivated.'
    post:
      operationId: deactivateContentPreparationTemplate
      summary: 'Deactivate a Content Preparation Template'
      responses:
        '202':
          # Accepted
          description: 'Deactivation of Content Preparation Template in progress'
        '204':
          # No Content
          description: 'Content Preparation Template deactivated'
        '400':
          # Bad Request: The request is malformed in a way not covered by one of the following more specific client errors
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          # Not Found
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '410':
          # Gone: This Content Preparation Template resource has been destroyed
          $ref: 'TS29571_CommonData.yaml#/components/responses/410'
        '413':
          # Payload Too Large: No request body allowed for this operation
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '414':
          # URI Too Long
          $ref: 'TS29571_CommonData.yaml#/components/responses/414'
        '415':
          # Unsupported Media Type
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '500':
          # Internal Server Error
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          # Service Unavailable
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
